### PR TITLE
Update erlcass with keyspace init & pagination support

### PR DESCRIPTION
**Pull request by exjesper**
Also:
* Update to c++ driver 2.15.0
* Add flexibility to CASS_VALUE_TYPE_TEXT by supporting atoms
* Add flexibility to CASS_VALUE_TYPE_DOUBLE by implicilty converting int64 -> double
* Inrease erlang connect timeout to catch all callbacks (as c++ driver has 5s already)

### CODE REVIEW

**Comment by exjesper** [comment]
Example usage of pagination in elixir:
```
    Stream.resource(
      fn ->
        {:ok, stm} = :erlcass.bind_prepared_statement(identifier)

        :ok =
          case values do
            [_ | _] -> :erlcass.bind_prepared_params_by_index(stm, values)
            _other -> :ok
          end

        :ok = :erlcass.set_paging_size(stm, page_size)
        page_task = Task.async(fn -> :erlcass.execute_paged(stm, identifier) end)
        {stm, page_task}
      end,
      fn
        :done ->
          {:halt, :done}

        {stm, page_task} ->
          case Task.await(page_task, page_timeout) do
            {:ok, columns, rows, true} ->
              process_erlcass_page(style, columns, rows, {
                stm,
                Task.async(fn -> :erlcass.execute_paged(stm, identifier) end)
              })

            {:ok, columns, rows, false} ->
              process_erlcass_page(style, columns, rows, :done)
          end
      end,
      fn _ -> :ok end
    )
```

**Comment by exjesper** [comment]
It's kind of a grab-bag of changes I've done for a project. Prefer not to maintain a fork so if it's something that can be added to upstream erlcass it would be nice. Could work on splitting it out into separate PR's if that's required but I'll let you review first if it's something you would like to have added.

**Comment by silviucpp** [comment]
Hello I daftly looked over your PR and seems lot of changes in different areas without link between them. Will be nice if you can split it.

Also the PR is missing tests for the new feature is adding and also pagination is not documented in the readme.

**Comment by silviucpp** [comment]
Will close this. Please break it into small pieces. and resend it if you are interested.

**Pull request closed without merging**
