### PR TITLE
install PPA only on ubuntu 14.04

### LINKED ISSUE #31: build_deps.sh overriding libuv install in Ubuntu 16.04
Hi!

I'm updating my TravisCI config file, and I'm using the Xenial Ubuntu (16.04) environment. This environment already comes with the correct libuv version (v1 instead of v0), however, in my Travis executions, I see that upon running `build_deps.sh` my existing version is downgraded to v0 in some weird way. Is it possible that, like for the CentOS configuration, you could add a check that verifies if libuv is available and only proceed if it's not?

It would be invaluable for me to get this working without rough edges :)

Thanks,

### PR DESCRIPTION
**Pull request by goncalotomas**
These changes should fix #31 .
`lsb_release -sr` returns the exact version (e.g. 16.04, 18.04 or 14.04) so we can use it to conditionally add the PPA only in 14.04.

For the remaining cases, I've added an additional check: if libuv exists, there is no need to try and install it again.

### CODE REVIEW

**Comment by silviucpp** [comment]
Looking to your code on Ubuntu > 14.04 if you have libuv installed the other deps are not checked.

sudo apt-get -y install g++ make cmake libssl-dev are executed only if is not installed libuv.

sudo apt-get -y install on an existing packet is not doing anything for this reason maybe only that ppa shouldn't be executed on > 14.04

**Comment by silviucpp** [comment]
@goncalotomas What's your opinion on this ? I mean I have a feeling that the proper fix is to limit the execution of `sudo apt-add-repository -y ppa:linuxjedi/ppa` on 14.04 only. 

All other can execute. because if a packet is already installed the apt-get will skip it.

**Comment by goncalotomas** [comment]
I agree with your comments. I think any `sudo apt install` will be ignored if the dependencies already exist, and it is important that we check for the existence of all of them. I will update my code accordingly :)

**Comment by silviucpp** [comment]
Thanks ! I'm glad to merge this fix !

**Comment by silviucpp** [comment]
Yes looks good ! thanks a lot

**Comment by goncalotomas** [comment]
No problem!
When you have the time, I would love to get these changes into the hex package. If you could tag a new release with these changes that would be awesome :)

Thanks,

**Comment by silviucpp** [comment]
Published

**Comment by silviucpp** [comment]
Better (I didn't tested but you get the idea):

```
$ubuntu_version=$(lsb_release -sr)
if [[ $ubuntu_version == "14.04" ]]; then
    # system is Ubuntu 14.04, need to install PPA and possibly override libuv
    sudo apt-add-repository -y ppa:linuxjedi/ppa
    LIBUDEV_PACKAGE_NAME=libuv-dev
else
    LIBUDEV_PACKAGE_NAME=libuv1-dev
fi
sudo apt-get -y update
sudo apt-get -y install g++ make cmake libssl-dev $LIBUDEV_PACKAGE_NAME
```

What do you think ? also can you test that's the proper fix ?

**Comment by goncalotomas** [comment]
Agreed. In regards to testing, I can't test on Ubuntu other than on my TravisCI builds, but I can help you configure TravisCI for erlcass such that it tests on Trusty and Xenial at the same time. Would you like some help configuring Travis?

**Comment by silviucpp** [comment]
I'm not interesting on 14.04 but will be great to have TravisCI for 16.04. So any help is appreciated. But fix above works for you on your TravisCI builds ?

**Comment by goncalotomas** [comment]
OK, I managed to get a working travis config for Xenial. Please go into https://travis-ci.org/silviucpp/erlcass (don't forget to log in with your GitHub account) and activate TravisCI for this repository.

Please let me know once you activated Travis so that I can submit the PR with the changes - otherwise we will not trigger TravisCI :)

**Comment by goncalotomas** [comment]
And yes, it would appear that in my fork of erlcass, the travis build succeeded, which would indicate that the above fix works :)

**Comment by silviucpp** [comment]
Can you push a new pull request with:

```
$ubuntu_version=$(lsb_release -sr)
if [[ $ubuntu_version == "14.04" ]]; then
    # system is Ubuntu 14.04, need to install PPA and possibly override libuv
    sudo apt-add-repository -y ppa:linuxjedi/ppa
    LIBUDEV_PACKAGE_NAME=libuv-dev
else
    LIBUDEV_PACKAGE_NAME=libuv1-dev
fi
sudo apt-get -y update
sudo apt-get -y install g++ make cmake libssl-dev $LIBUDEV_PACKAGE_NAME
```

**Comment by goncalotomas** [comment]
Of course! I totally forgot to add that.
Have you activated Travis for this repository?

**Comment by silviucpp** [comment]
No I didn't . I didn't yet used it in any of the projects. I need to read a bit regarding it.

**Comment by goncalotomas** [comment]
It's very useful. On every commit you push to the repository, it runs tests and emails you if they fail or pass. This basically let's you track when and how bugs are introduced in erlcass.

I use it on all of my public projects :)

**Comment by silviucpp** [comment]
Yes it is . Does it support also OSX ? because erlcass runs on OSX as well

**Comment by goncalotomas** [comment]
It does support OSX, but you cannot easily specify which version of it to run, so configuring for it is a bit trickier. Here is [an example configuration](https://github.com/erlang/rebar3/blob/master/.travis.yml#L14-L20) with OSX support.

**Pull request merged**
