### PR TITLE
Remove lager dependency, use native OPT21+ logger.

### PR DESCRIPTION
**Pull request by csrl**
Erlcass as a library is consumed by applications and does not stand on its own.  As such it should not force using additional logging facilities that the application does not use. The lager dependency brings in multiple sub dependencies as well.  OTP 21+ provide reasonable logging facilities sufficient for the use in Erlcass.

This PR removes lager and it's dependencies.  The code change is a matter of swapping `lager` for `logger` in include/erlcass_internals.hrl

### CODE REVIEW

**Comment by silviucpp** [comment]
Hello,

We removed the OTP 19/20/21  from travis because are not longer supported there out of the box. Idea is that internally we are using this library in OTP 19 as well and also the main issue is the fact that we need to be able to send the logs in graylog. And we are using a module for lager which is doing this. Lager seems is not able to catch the logs from OTP21 logger .. 

Other guys asked for another library we have as well to get rig of lager https://github.com/silviucpp/erlkaf/pull/9#issuecomment-944781554

**Comment by silviucpp** [comment]
@csrl Are you talking about an ENV variable or can you elaborate on how you want to achieve this ? If it's an env variable I think you can also use rebar3 dynamic config to also add lagger as dependency in case it's used.

**Comment by csrl** [comment]
I was thinking as an config field, for example:
```erlang
{erlcass, [{log_facility, <<"lager">>}, {log_level, 3}, {cluster_options, [...]}]}
```

**Comment by csrl** [comment]
To be clear - that approach would require making erlcass_log.erl a named process and update the minimal use of ERROR/INFO_MSG macros in erlcass.erl to send the log messages to erlcass_log.

**Comment by silviucpp** [comment]
A better idea might be to use a custom define like:

```erl
-ifdef(USE_LAGER).
  %% Log macros will use lager
-else.
  %% Log macros will use logger
-endif.
```

And somehow to define that macro from rebar3 . maybe different profiles to build with logger or lager ?

**Comment by silviucpp** [comment]
I implemented this in master and I will publish a package today.

**Pull request closed without merging**
