### PR TITLE
Return column names and types along with results

### PR DESCRIPTION
**Pull request by cibingeorge**
This returns result of the form
```
{ok, 
  {
    [{row1...}, {row2...}], 
    [{<<"column_name">>, type}, ]
  }
}
```
With this form of result, I can construct a map.

### CODE REVIEW

**Comment by cibingeorge** [comment]
I am trying to write a ecto cassandra like adapter on top of erlcass. Hit this issue where i dont know what columns are returned for select * queries.

**Comment by silviucpp** [comment]
Hello @cibingeorge, using `select *` it's a bad thing. The prepared statements are going crazy in case you alter that table and for example add one more column or delete an existing one. 

Maybe this was fixed in the last cassandra version (I didn't tested) yet.

Anyway beside this detail I need to think about the implications of this change. But most probably best way will be to return them like:

`{ok, [{<<"column_name">>, type}, ..],  [{row1...}, {row2...}]}`

Foe peoples that don't care about column name and type they can match much simple like:

`{ok, _Cols, Rows} = erlcass:execute(..)`

Silviu

**Comment by cibingeorge** [comment]
Not sure what the effect of schema changes on select * on prepared statements. This is mostly useful for one off queries which are unprepared.

This change is not backward compatible. So you might want to merge this on a major version upgrade im guessing. I can swap the ordering of rows and column data.

**Comment by silviucpp** [comment]
I see multiple projects returning also the columns and yes I found this useful myself in some projects as well where you want to return the result json encoded for example. Having both columns and rows it's very simple. 

But instead:

`{ok, {[{row1...}, {row2...}], [{<<"column_name">>, type}, ]}}`

might be better to return:

`{ok, [{<<"column_name">>, type}], [{row1...}, {row2...}] }`

- column first and then rows
- remove the inner tuple as well {ok, Cols, Rows} instead {ok, {Cols, Rows}} as it is now

And yes I will have to fix the tests and see the impact on benchmarks and merge it in a next major release. 

Thanks for your contribution,

Silviu

**Comment by cibingeorge** [comment]
I reworked on the code. Fixed the tests. Check it out and let me know if you need anyting else.

**Comment by silviucpp** [comment]
Hello,

It's ok. I will integrate it into the next major release when anyway I'm planning to change what insert and updates statements are returning. 

Instead {ok, []} to return only ok. It's no point here to return all the time an empty list. 

Thanks a lot for your contribution !

Silviu

**Comment by silviucpp** [comment]
Integrated in  3.0_release branch already with few changes.

**Pull request closed without merging**
