### PR TITLE
Add OSX compile step in TravisCI build

### PR DESCRIPTION
**Pull request by goncalotomas**

### CODE REVIEW

**Comment by silviucpp** [comment]
I already fixed this

**Comment by silviucpp** [comment]
When I'll have some time I'll try to add a rpm based system as well (maybe Cent OS). I didn't tested here for some years and for sure some packages might changed.

**Comment by goncalotomas** [comment]
Great! 🎉 
With compatibility for Ubuntu and OSX being tested with TravisCI it shouldn't be so hard to add CentOS, although I suspect you might need to test it from a container. Time will tell.

In the mean time, would it possible to get `3.2.3` published on Hex?

Thank you so much for the responsiveness.

**Comment by silviucpp** [comment]
Done

**Comment by silviucpp** [comment]
I start liking trevis :) I see I can start also cassandra and run the common tests and then publish the coverage as well.

**Comment by goncalotomas** [comment]
Exactly! Take a moment to read the documentation and you'll see how it can help make erlcass be more robust.

This will tell your users that since the software is well tested, they can use it with confidence. You can take a look at [FMKe's .travis.yml](https://github.com/goncalotomas/FMKe/blob/master/.travis.yml) since I run docker containers and run coverage tests as well.

erlcass is getting lots of [downloads on hex](https://hex.pm/packages/erlcass), which is always great to see 👍

**Comment by silviucpp** [comment]
Erlcass it's used without no issue in a system with high load: https://www.wowapp.com/ . So it's safe and maintained. Of course there are multiple features still available in the Datastax driver which are not exposed but provides more than enough.

**Comment by goncalotomas** [comment]
Great, that is very reassuring 💪 

There is a website within the Erlang community called [erlang-companies](https://erlang-companies.org). Perhaps someone from the company can add it to the list of companies using Erlang :)

**Pull request closed without merging**
